#!/bin/sh

dir=`pwd`

[ "$dir" == "$HOME" ] && echo "Cannot run script in home directory." && exit
[ ! -e .conkyrc ] && echo "Error: .conkyrc not found." && exit
[ ! -e .config/openbox/autostart ] && echo "Error: autostart not found." && exit
[ ! -e .config/autostart/gmixer-trayicon.desktop ] && echo "Error: gmixer-trayicon.desktop not found." && exit

rm -f ~/.conkyrc
ln -s $dir/.conkyrc ~

rm -f ~/.config/openbox/autostart.sh
rm -f ~/.config/openbox/autostart
mkdir -p ~/.config/openbox/
ln -s $dir/.config/openbox/autostart ~/.config/openbox/

rm -f ~/.config/autostart/gmixer-trayicon.desktop
mkdir -p ~/.config/autostart/
ln -s $dir/.config/autostart/gmixer-trayicon.desktop ~/.config/autostart/
